controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Defino una nueva ruta (gentileza de Alejandro)
app_aleatorio_v4:
    path: /mi_aleatorio_44
    controller: App\Controller\AleatorioController::mialeatorio3
